# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-16 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('name', models.CharField(max_length=220)),
                ('surname', models.CharField(max_length=220)),
                ('street', models.CharField(max_length=220)),
                ('city', models.CharField(max_length=220)),
                ('phone', models.CharField(max_length=220)),
                ('github', models.CharField(max_length=220)),
                ('facebook', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('technology', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=220)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
