# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-16 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170516_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('imie', models.CharField(max_length=220)),
                ('nazwisko', models.CharField(max_length=220)),
                ('miasto', models.CharField(max_length=220)),
                ('telefon', models.CharField(max_length=220)),
                ('email', models.CharField(max_length=220)),
                ('github', models.CharField(max_length=220)),
                ('facebook', models.CharField(max_length=220)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
